server:
  port: 8081

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          autoCreateTopics: true
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: svc2-errors

      bindings:
        input:
          group: service2
          destination: svc2-input
          contentType: application/json
          consumer:
            max-attempts: 1
        output:
          destination: svc1-input
          contentType: application/json

